/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLogic;

import BusinessLogic.Calculadora_Tarifa;
import Actors.Bicicleta;
import Actors.Carro;
import Actors.Moto;
import javax.swing.JOptionPane;

/**
 *
 * @author diegoalejo
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    Recibo r=new Recibo();
    Calculadora_Tarifa ct=new Calculadora_Tarifa();
    
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        cbxAuto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabPlaca = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Parqueadero Esteban");

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        cbxAuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Carro", "Bicicleta", " " }));
        cbxAuto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAutoItemStateChanged(evt);
            }
        });
        cbxAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAutoActionPerformed(evt);
            }
        });

        jLabel2.setText("tipo");

        jLabel3.setText("Horas");

        jlabPlaca.setText("Placa");

        jLabel5.setText("Color");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jlabPlaca)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcular)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbxAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHoras)
                                .addComponent(txtColor)
                                .addComponent(txtPlaca)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalir)
                    .addComponent(btnCalcular))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void cbxAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAutoActionPerformed
      
        if(cbxAuto.getSelectedItem().equals("Bicicleta")){
            jlabPlaca.setText("Marca");
        }
    }//GEN-LAST:event_cbxAutoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        
        
        if(cbxAuto.getSelectedItem().equals("Moto")){
         r.m=new Moto (txtColor.getText(),txtPlaca.getText());
         int dhoras= Integer.parseInt(txtHoras.getText());
         double calculo = ct.Calculartarifa(r.m.Valorxhora(), dhoras);    
         JOptionPane.showMessageDialog(null, "Color : "+r.m.getColor() +"\n Placa : "
                 +r.m.getPlaca()+"\n Valor a pagar : "+ calculo );
         txtColor.setText("");
         txtPlaca.setText("");
         txtHoras.setText("");
        }
        
         if(cbxAuto.getSelectedItem().equals("Carro")){
         r.c=new Carro (txtColor.getText(),txtPlaca.getText());
         int dhoras= Integer.parseInt(txtHoras.getText());
         double calculo = ct.Calculartarifa(r.c.Valorxhora(), dhoras);   
         JOptionPane.showMessageDialog(null,"Color : "+ r.c.getColor() +
                 "\n  Placa : "+r.c.getPlaca()+"\n Valor a pagar : "+ calculo );
         txtColor.setText("");
         txtPlaca.setText("");
         txtHoras.setText("");
        }
         
         
         
         if(cbxAuto.getSelectedItem().equals("Bicicleta")){
         r.b=new Bicicleta (txtColor.getText(),txtPlaca.getText());
         int dhoras= Integer.parseInt(txtHoras.getText());
         double calculo = ct.Calculartarifa(r.b.Valorxhora(), dhoras);  
         JOptionPane.showMessageDialog(null,"Color  : "+ r.b.getColor()+" \n Marca : "+ r.b.getPlaca() +"\n Valor a Pagar : "+ calculo );
         txtColor.setText("");
         txtHoras.setText("");
        }
         
         
         
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cbxAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAutoItemStateChanged
        
    }//GEN-LAST:event_cbxAutoItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbxAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlabPlaca;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
